### ISSUE TITLE
LYWSD02MMC doesn't sync

### ISSUE THREAD

**Issue by davidthedolphin** [ashald/home-assistant-lywsd02#2]
Hello !

My LYWSD02MMC doesn't sync (maybe because it's a "MMC" ?).
HACS is installed and you repo too.
My automation :
```
trigger:
  - platform: time
    at: "04:00:00"
condition: []
action:
  - service: lywsd02.set_time
    metadata: {}
    data:
      mac: E7:2E:00:E2:71:01
mode: single
```
I have no error when it runs but nothings appends, the clock isn't synced (1 minute is still missing).
HA runs on rpi 3 and the pi clock is OK.
HAOS is up to date.
