### ISSUE TITLE
half-hour offset

### ISSUE THREAD

**Issue by Waldzio** [ashald/home-assistant-lywsd02#3]
Hello, thank you very much for this integration. It's very useful because I travel a lot by sea. I often change time zones, but not always according to the actual location; sometimes I do it earlier or later depending on how long we'll be at sea.

That's why I set the time zone on my phone, and I would like the watches to immediately synchronize with the time zone set on my phone. It works great, but the watches act up when we're in places like Sri Lanka, where it's GMT+05:30.

Unfortunately, your service doesn't accept tz_offset: 5.5.

Generally, my automation looks like this:

```yaml
alias: Synchronize Xiaomi Clock
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.z_flip_5_sm_f731b_current_time_zone
condition: []
action:
  - service: lywsd02.set_time
    data:
      mac: 77:2E:4592:44:34
      tz_offset: >-
        {{ ((state_attr('sensor.z_flip_5_sm_f731b_current_time_zone',
        'utc_offset') | float / 3600) | int // 1000 -1) | string }}
mode: single
```

It works only with full hour offset, but even manual invocation doesn't work anymore:

```yaml
service: lywsd02.set_time
data:
  mac: 77:2E:4592:44:34
  tz_offset: 5.5
```

Do you think you could somehow add the ability to handle tz_offset in the format X.X?

Thanks,
Waldek B.
